### ISSUE TITLE
调用 get_my_profile() 出错

### ISSUE THREAD

**Issue by fengzhichu** [Sorosliu1029/Jike-Metro#1]
调用 get_my_profile() 时，出现下面错误。
```python
my_profile = c.get_my_profile()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/jike/client.py", line 64, in get_my_profile
    return self.get_user_profile(username=None)
  File "/usr/local/lib/python3.6/site-packages/jike/client.py", line 99, in get_user_profile
    return User(**result['user'])
TypeError: __new__() got an unexpected keyword argument 'wechatOpenId'
```

**Comment by Sorosliu1029** [comment]
谢谢你的反馈
