### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by whuchenshuo** [Sorosliu1029/Jike-Metro#15]
字段已经保持更新
requests版本 2.21.0
报错如下：
```
Traceback (most recent call last):
  File "file1.py", line 6, in <module>
    hehe = c.create_my_post(result)
  File "/usr/local/lib/python3.5/dist-packages/jike/client.py", line 214, in create_my_post
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.jike.ruguoapp.com/1.0/originalPosts/create
```

**Comment by Sorosliu1029** [comment]
看 HTTP error code 401，应该是你的 jike token 过期了，请重新扫码登录。

**Comment by whuchenshuo** [comment]
已经解决～～谢谢
