### ISSUE TITLE
__new__() got an unexpected keyword argument

### ISSUE THREAD

**Issue by xorange** [Sorosliu1029/Jike-Metro#17]
# 版本：
Python 3.6.5
jike 0.5.0

# 现象：
1. 调用`c.get_my_profile`失败，报告`TypeError: __new__() got an unexpected keyword argument 'trailingIcons'`
2. 调用`c.get_my_collection()`失败，报告`TypeError: __new__() got an unexpected keyword argument 'shareCount'`
3. 调用`c.get_news_feed()`失败，报告`TypeError: __new__() got an unexpected keyword argument 'shareCount'`

# 以下是log：

```
>>> import jike
>>> c = jike.JikeClient()
>>> c.get_my_profile()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/jike/client.py", line 81, in get_my_profile
    return self.get_user_profile(username=None)
  File "/anaconda3/lib/python3.6/site-packages/jike/client.py", line 116, in get_user_profile
    return User(**result['user'])
TypeError: __new__() got an unexpected keyword argument 'trailingIcons'
>>> c.get_my_collection()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/jike/client.py", line 86, in get_my_collection
    self.collection.load_more()
  File "/anaconda3/lib/python3.6/site-packages/jike/objects/base.py", line 176, in load_more
    more = [converter[item['type']](**item) for item in result['data']]
  File "/anaconda3/lib/python3.6/site-packages/jike/objects/base.py", line 176, in <listcomp>
    more = [converter[item['type']](**item) for item in result['data']]
TypeError: __new__() got an unexpected keyword argument 'shareCount'
>>> c.get_news_feed()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/jike/client.py", line 100, in get_news_feed
    self.news_feed.load_more()
  File "/anaconda3/lib/python3.6/site-packages/jike/objects/base.py", line 215, in load_more
    more = [converter[item['type']](**item) for item in result['data']]
  File "/anaconda3/lib/python3.6/site-packages/jike/objects/base.py", line 215, in <listcomp>
    more = [converter[item['type']](**item) for item in result['data']]
TypeError: __new__() got an unexpected keyword argument 'shareCount'
```

# References

参考了以下issue，可能跟新版有关？
#1 
#2 
#4 
#11 

刚开始学习教程：https://www.0x2beace.me/Jike-Metro/

Thanks your work!

**Comment by Sorosliu1029** [comment]
确认和新版有关，可以直接在 jike/objects  目录下的相应文件里增加新字段

**Comment by Mustela-sibirica** [comment]
你好,解决了吗?遇到了同样的问题......

**Comment by xorange** [comment]
> 你好,解决了吗?遇到了同样的问题......

我还没尝试，但作者已经给了足够的信息了。在Issue里可以找一下，有较多类似原因的修复提交，应该可以参考着自己改一下

**Comment by xorange** [comment]
> 你好,解决了吗?遇到了同样的问题......

以`jike.JikeClient().get_my_profile()`为例，输出的error里面会显示实际缺失的字段

> TypeError: __new__() got an unexpected keyword argument 'shareCount'

最后在jike/objects/user.py加上所有缺失的字段就可以了

```
'trailingIcons',
'statsCount',
'wechatUnionId',
'medals',
'profileTags',
'school',
```

**Comment by xorange** [comment]
在jike/objects/message.py的PUBLIC_FIELDS里添加：

```
'shareCount',
'urlsInText',
'isFeatured',
'attachedComments',
'rollouts',
'video',
```

就可以跑通如下接口：

```
my_profile = c.get_my_profile()

my_collection = c.get_my_collection()

news_feed = c.get_news_feed()
```

jike.__version: 0.5.0
