### ISSUE TITLE
最近经常出现500或502，请问下

### ISSUE THREAD

**Issue by xorange** [Sorosliu1029/Jike-Metro#18]
最近使用时经常出现：

> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://app.jike.ruguoapp.com/1.0/messages/history

或

> requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://app.jike.ruguoapp.com/1.0/messages/history

调用栈如下：

> Traceback (most recent call last):
  File "./jikeTopicPictures.py", line 65, in <module>
    messages = topic.load_more(limit=LOAD_LIMIT)
  File "/anaconda3/lib/python3.6/site-packages/jike/objects/base.py", line 210, in load_more
    result = super().fetch_more(self.endpoint, payload)
  File "/anaconda3/lib/python3.6/site-packages/jike/objects/base.py", line 143, in fetch_more
    res.raise_for_status()
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

不太知道如何调试，来请教一下。谢谢

**Comment by xorange** [comment]
> 
> 不太知道如何调试，来请教一下。谢谢

是只能等网络条件重新试试，还是哪里有可能有问题呢

**Comment by whuchenshuo** [comment]
> > 不太知道如何调试，来请教一下。谢谢
> 
> 是只能等网络条件重新试试，还是哪里有可能有问题呢

可能是jike token过期的问题
