### ISSUE TITLE
调用 get_my_profile() 出错

### ISSUE THREAD

**Issue by Immmortal** [Sorosliu1029/Jike-Metro#2]
调用 get_my_profile() 时，出现下面错误。应该是和第一个issue类似的问题。
```
>>> c.get_my_profile()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\jike\client.py", line 64, in get_my_profile
    return self.get_user_profile(username=None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jike\client.py", line 99, in get_user_profile
    return User(**result['user'])
TypeError: __new__() got an unexpected keyword argument 'wechatUserInfo'
```

**Comment by Sorosliu1029** [comment]
已修复，👉 [Commit](https://github.com/Sorosliu1029/Jike-Metro/commit/5304cfb2c50d69080d4dcee733939862a914bac7#diff-f15780f53185f4e3813cb7d39ca4f02eR44)
