### ISSUE TITLE
调用 get_my_profile() 出错

### ISSUE THREAD

**Issue by zmkoo000** [Sorosliu1029/Jike-Metro#4]
```
Traceback (most recent call last):

  File "<ipython-input-3-847dea99bf76>", line 1, in <module>
    c.get_my_profile()

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\jike\client.py", line 64, in get_my_profile
    return self.get_user_profile(username=None)

  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\lib\site-packages\jike\client.py", line 99, in get_user_profile
    return User(**result['user'])

TypeError: __new__() got an unexpected keyword argument 'createdAt'
```

**Comment by Sorosliu1029** [comment]
Fixed by [commit e1d26f4](https://github.com/Sorosliu1029/Jike-Metro/commit/e1d26f407540da4e9741265f353fbd03aea23056)
