### ISSUE TITLE
调用get_recommended_topic()出错

### ISSUE THREAD

**Issue by AlloyKingdom** [Sorosliu1029/Jike-Metro#5]
recommended_topics = c.get_recommended_topic()
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    recommended_topics = c.get_recommended_topic()
  File "D:\python\lib\site-packages\jike\client.py", line 338, in get_recommended_topic
    topics.load_more()
  File "D:\python\lib\site-packages\jike\objects\base.py", line 174, in load_more
    more = [self.converter(**item) for item in result['data']]
  File "D:\python\lib\site-packages\jike\objects\base.py", line 174, in <listcomp>
    more = [self.converter(**item) for item in result['data']]
TypeError: __new__() got an unexpected keyword argument 'type'

**Comment by Sorosliu1029** [comment]
可以在 [objects/topic.py](https://github.com/Sorosliu1029/Jike-Metro/blob/master/jike/objects/topic.py#L42) 里添加一行 `type`
