### ISSUE TITLE
获取用户动态出错

### ISSUE THREAD

**Issue by jiefangjun** [Sorosliu1029/Jike-Metro#7]
报错信息
> Traceback (most recent call last):
  File "like.py", line 14, in <module>
    ceo_posts = c.get_user_post(username='82D23B32-CF36-4C59-AD6F-D05E3552CBF3')
  File "/usr/lib/python3.6/site-packages/jike/client.py", line 121, in get_user_post
    posts.load_more(limit)
  File "/usr/lib/python3.6/site-packages/jike/objects/base.py", line 176, in load_more
    more = [converter[item['type']](**item) for item in result['data']]
  File "/usr/lib/python3.6/site-packages/jike/objects/base.py", line 176, in <listcomp>
    more = [converter[item['type']](**item) for item in result['data']]
TypeError: __new__() got an unexpected keyword argument 'urlsInText'

**Comment by JasonKhew96** [comment]
https://github.com/Sorosliu1029/Jike-Metro/blob/master/jike/objects/message.py#L32
已经解决，请更新至最新版本，确定没问题关掉issue吧
